const cities = [
  "Almaty, Kazakhstan",
  "Astana, Kazakhstan",
  "Shymkent, Kazakhstan",
  "Karaganda, Kazakhstan",
  "Aktobe, Kazakhstan",
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Sharjah, UAE",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Doha, Qatar",
  "Kuwait City, Kuwait",
  "Muscat, Oman",
  "Manama, Bahrain",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Izmir, Turkey",
  "Baku, Azerbaijan",
  "Tashkent, Uzbekistan",
  "Bishkek, Kyrgyzstan",
  "Dushanbe, Tajikistan",
  "Ashgabat, Turkmenistan",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Novosibirsk, Russia",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Paris, France",
  "Lyon, France",
  "Marseille, France",
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "New York, USA",
  "Los Angeles, USA",
  "Chicago, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Nagoya, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Taipei, Taiwan",
  "Hong Kong, China",
  "Beijing, China",
  "Shanghai, China",
  "Bangkok, Thailand",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Singapore, Singapore",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Delhi, India",
  "Mumbai, India",
  "Bangalore, India",
  "Kathmandu, Nepal",
  "Colombo, Sri Lanka",
  "Dhaka, Bangladesh",
  "Lagos, Nigeria",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Nairobi, Kenya",
  "Cairo, Egypt",
  "Casablanca, Morocco",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Mexico City, Mexico",
];

export default cities;
